Repository EduardoSimon/budget.io, pull requests merged in 2023-10, with the labels that each got.

#24 Refactor the account balance
  Gemfile
  Gemfile.lock
  Makefile
  README.md
  app/controllers/movements_controller.rb
  app/jobs/pull_account_movements_job.rb
  app/models/account.rb
  app/models/budget.rb
  app/services/open_banking_connector.rb
  app/views/accounts/_card.html.erb
  app/views/budgets/show.html.erb
  bin/solargraph
  db/migrate/20230815205057_convert_balance_decimal_to_money.rb
  db/schema.rb
  db/seeds.rb
  test/controllers/accounts_controller_test.rb
  test/controllers/budgets_controller_test.rb
  test/controllers/movements_controller_test.rb
  test/factories/account.rb
  test/integration/movements_test.rb
  test/jobs/pull_account_movements_job_test.rb
  test/models/budget_test.rb
  test/test_helpers/mock_client.rb
Labels: hacktoberfest

#47 Fixes the Institutions migration isssue
  README.md
  db/migrate/20221229143942_add_institutions_from_open_banking_provider.rb
  db/seeds.rb
  lib/tasks/institutions_data.rake
Labels: bug, hacktoberfest

#46 Enhancement for the `make lint` command
  Makefile
Labels: enhancement, hacktoberfest

#49 chore(#35): add docker + Makefile for local dev
  .github/workflows/main.yml
  Dockerfile
  Makefile
  db/seeds.rb
  docker-compose.ci.yml
  docker-compose.test.yml
  docker-compose.yml
Labels: hacktoberfest

#50 chore: adapt database name to repository name
  Makefile
  config/database.yml
Labels: hacktoberfest

#51 ci: update checkout action to prevent deprecation warnings
  .github/workflows/main.yml
Labels: hacktoberfest

#48 Remove AuthSession from the Seed
  README.md
  app/models/auth_session.rb
  db/seeds.rb
  test/models/auth_session_test.rb
Labels: hacktoberfest
